"""Chain-of-Thought (M2) prompt and output parsing.

M2 reuses the SAME fine-tuned model with a different prompt (prompt-only CoT). The model
was fine-tuned on transcription, not reasoning, so it may not follow the format — the
parser falls back to using the whole output as the answer and notes that in the log, so
CER/WER reflect what the model actually produced.
"""
from __future__ import annotations

# Marker the model is asked to put before its final answer. Tunable (see spec open items).
FINAL_MARKER = "Final:"

# Note added to the log when the model did not emit the marker.
NO_MARKER_NOTE = "[no 'Final:' marker found — using full output as the transcription]"

# Prompt for M2. Asks for a short description of ambiguous strokes, then the final answer
# on its own line prefixed with the marker. Mirrors the SP-1 prompt's plain style.
COT_PROMPT = (
    "transcribe the handwritten text. First briefly describe the distinctive stroke "
    "shapes of any ambiguous characters. Then on a new line write only the final "
    "transcription prefixed exactly with 'Final:'\n"
)


def parse_cot(raw: str) -> tuple[str, str]:
    """Split a raw CoT generation into (final_text, reasoning_log).

    If 'Final:' appears, the text after its LAST occurrence is the answer and everything
    before it is the reasoning log. Otherwise the whole output is the answer and the log
    records that the marker was missing.

    Args:
        raw: The raw string generated by the model.

    Returns:
        A tuple of (final_text, reasoning_log) where:
        - final_text: The answer portion after the last 'Final:' marker, stripped of
          surrounding whitespace. Falls back to the full stripped output if no marker.
        - reasoning_log: Everything before the last 'Final:' marker, stripped. When no
          marker is found this contains NO_MARKER_NOTE so the caller can log/audit it.
    """
    if FINAL_MARKER in raw:
        # rpartition splits on the LAST occurrence, so multiple 'Final:' lines are handled
        # correctly — only the final answer (rightmost) is extracted.
        reasoning, _, final = raw.rpartition(FINAL_MARKER)
        return final.strip(), reasoning.strip()

    # Fallback: the model skipped the format. Return the whole output as the transcription
    # so that CER/WER still reflect what the model actually produced. Annotate the log so
    # analysis scripts can filter these cases and flag them in the thesis results.
    stripped = raw.strip()
    return stripped, f"{stripped}\n{NO_MARKER_NOTE}".strip()
